### ISSUE TITLE
Adding own service

### ISSUE THREAD

**Issue by nightfreak** [Sroose/homebridge-loxone-ws#3]
Hey there...

at first I want to thank you for the great work you have done!
It's working like a charm :-)

But I have problems adding an additional service. Since I am not very familiar with JS, maybe you can help me out at this point.

When I modify line 37 in SwitchItem.js:
from: var otherService = new this.homebridge.hap.Service.Switch();
to: var otherService = new this.homebridge.hap.Service.Fan();
The icon in Homekit changes correctly to a fan icon and everything works fine.

But when I try to create an additional service (to not loose the switch service), it does not work.

What have I done:
- I copied and renamed SwitchItem.js to FanItem.js
- Then I replaced all SwitchItem strings in FanItem.js to FanItem.
- Then I added the exports in ItemFactory.js:
exports.Fan = require('../items/FanItem.js');

- Then I added following case to the checkCustomAttrs in ItemFactory.js:
    } else if(item.name.startsWith('Cooler')) {
        item.type = "Fan";

    }

After restarting homebridge, I get this error:

/usr/local/lib/node_modules/homebridge-loxone-ws/items/FanItem.js:12
    FanItem.super_.call(this, widget,platform,homebridge);
                  ^

TypeError: Cannot read property 'call' of undefined
    at new FanItem (/usr/local/lib/node_modules/homebridge-loxone-ws/items/FanItem.js:12:19)
    at exports.Factory.parseSitemap (/usr/local/lib/node_modules/homebridge-loxone-ws/libs/ItemFactory.js:58:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-loxone-ws/index.js:67:34)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/request/request.js:1001:12)

**Comment by Sroose** [comment]
Hi,
The description of your actions looks correct at first sight. I would need to test this out.
But note that instead of copying the Switch, you could make a child component similar to the Lightbulb item which is a descendant of Switch. That saves some code since you'll just override the getOtherServices method.

**Comment by nightfreak** [comment]
ooooh, I noticed that I also have to add this to index.js
Utility.addSupportTo(ItemFactory.Fan, ItemFactory.AbstractItem);

Now everything works fine :-)

Thank you!
