### ISSUE TITLE
Connection fails

### ISSUE THREAD

**Issue by cuni0716** [Sroose/homebridge-loxone-ws#37]
Hi, i try to install on my home and it appears to be all ok.
The reading of the config file works fine and send all my rooms and accessories to apple homekit correctly, but the try to connect all the time and the commands doesn't work.

Can you help me please!!

My Loxone Miniserver version is: 8.1.11.11 and i run homebridge in macOS 10.14

Thanks in advance

<img width="1050" alt="screenshot 2018-10-04 at 20 13 14" src="https://user-images.githubusercontent.com/9133999/46493962-f4b06400-c811-11e8-8960-7abb4216a1f0.png">

And sometimes, when i trigger a `send message` to some accessory i receive this error:
```[10/5/2018, 12:16:58 AM] [Loxone] [switch] iOS - send message to Menjador of Cuina in Cuina: On
/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:190
    this.connection.send(this._auth.prepare_control_command(control, command));
                                    ^

TypeError: Cannot read property 'prepare_control_command' of undefined
    at API.send_control_command (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:190:37)
    at API.send_cmd (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/API.js:203:10)
    at WSListener.sendCommand (/usr/local/lib/node_modules/homebridge-loxone-ws/libs/WSListener.js:140:13)
    at LightbulbItem.SwitchItem.setItemState (/usr/local/lib/node_modules/homebridge-loxone-ws/items/SwitchItem.js:62:22)
    at Characteristic.On.emit (events.js:182:13)
    at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at HAPServer.emit (events.js:182:13)```

**Comment by cuni0716** [comment]
they was a problem with my loxone miniserver version, fixed updating it!
