### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by kaumi345** [Sroose/homebridge-loxone-ws#4]
Hi,

after starting my Homeride first everything looks ok but then I get this error:
I hope you could help me.

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 012-34-567 │     
    └────────────┘     
                       
[2016-12-09 18:01:59] Homebridge is running on port 51826.
buffer.js:663
    throw new RangeError('index out of range');
    ^

RangeError: index out of range
    at checkOffset (buffer.js:663:11)
    at Buffer.readDoubleLE (buffer.js:856:5)
    at new EventWeather (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/Message/EventWeather.js:21:39)
    at Connection.handle_message (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/Connection.js:189:34)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/Connection.js:98:14)
    at emitOne (events.js:90:13)
    at WebSocketConnection.emit (events.js:182:7)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/websocket/lib/WebSocketConnection.js:524:26)
    at /usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (node.js:376:9)

**Comment by kaumi345** [comment]
For first I deactivated the EventWeather.js now the home bridge is running, I hope someone could help me to fix it

**Comment by Sroose** [comment]
Hello,

this seems to be an issue in the websocket project. Could you open the issue [there](https://github.com/alladdin/node-lox-ws-api)?

**Comment by kaumi345** [comment]
Fixed in websocket Project version 0.2.4
