### ISSUE TITLE
Homebridge Loops After connection

### ISSUE THREAD

**Issue by Flymaik** [Sroose/homebridge-loxone-ws#52]
Hi, 

after installing the plugin at Homebridge the pi loops at startup  and trying to get connected to Loxone.

Can anybody help? Here the log:

-- Logs begin at Mon 2020-04-27 18:17:01 CEST. --
Apr 27 18:53:08 raspberrypi sudo[723]: pam_unix(sudo:session): session closed for user root
Apr 27 18:57:29 raspberrypi homebridge[332]: [4/27/2020, 18:57:29] [Config] Changes to config.json saved.
Apr 27 18:58:11 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...
Apr 27 18:58:11 raspberrypi homebridge[332]: [4/27/2020, 18:58:11] Got SIGTERM, shutting down Homebridge...
Apr 27 18:58:16 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Apr 27 18:58:16 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Apr 27 18:58:16 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Apr 27 18:58:16 raspberrypi systemd[1]: homebridge.service: Found left-over process 428 (homebridge-conf) in control group while starting unit. Ignoring.
Apr 27 18:58:16 raspberrypi systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Apr 27 18:58:16 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Apr 27 18:58:17 raspberrypi homebridge[975]: [4/27/2020, 18:58:17] Loaded config.json with 0 accessories and 2 platforms.
Apr 27 18:58:17 raspberrypi homebridge[975]: [4/27/2020, 18:58:17] ---
Apr 27 18:58:18 raspberrypi homebridge[975]: [4/27/2020, 18:58:18] Loaded plugin: homebridge-config-ui-x
Apr 27 18:58:18 raspberrypi homebridge[975]: [4/27/2020, 18:58:18] Registering platform 'homebridge-config-ui-x.config'
Apr 27 18:58:18 raspberrypi homebridge[975]: [4/27/2020, 18:58:18] ---
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] Loaded plugin: homebridge-http-opensprinkler-api
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] Registering accessory 'homebridge-http-opensprinkler-api.OPENSPRINKLER-STATION'
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] ---
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] Loaded plugin: homebridge-loxone-ws-adv
Apr 27 18:58:19 raspberrypi homebridge[975]: homebridge API version: 2.5
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] Registering platform 'homebridge-loxone-ws-adv.LoxoneWs'
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] ---
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] Loading 2 platforms...
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] [Config] Initializing config platform...
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] [Config] Spawning homebridge-config-ui-x with PID 1005
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] [Hauptserver] Initializing LoxoneWs platform...
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] [Hauptserver] Info: rooms array not configured. Adding every room.
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] [Hauptserver] object
Apr 27 18:58:19 raspberrypi homebridge[975]: New WS: 10.0.10.55:80
Apr 27 18:58:19 raspberrypi homebridge[975]: [4/27/2020, 18:58:19] [Hauptserver] Platform - Waiting 8 seconds until initial state is retrieved via WebSocket.
Apr 27 18:58:20 raspberrypi homebridge[975]: [4/27/2020, 18:58:20] [Hauptserver] LOXONE WS: connect
Apr 27 18:58:24 raspberrypi homebridge[975]: [4/27/2020, 18:58:24] [Config] Homebridge Config UI X v4.16.0 is listening on :: port 8080
Apr 27 18:58:27 raspberrypi homebridge[975]: [4/27/2020, 18:58:27] [Hauptserver] Platform - Retrieving initial config from http://xxxxxxx:yyyyyyyyyyy@10.0.10.55:80/data/LoxApp3.json
Apr 27 18:58:28 raspberrypi homebridge[975]: [4/27/2020, 18:58:28] [Hauptserver] Platform - The widget 'Lichterkette' of type LightControllerV2 is an item not handled.
Apr 27 18:58:28 raspberrypi homebridge[975]: [4/27/2020, 18:58:28] TypeError: Class constructor PlatformAccessory cannot be invoked without 'new'
Apr 27 18:58:28 raspberrypi homebridge[975]: at LightbulbItem.AbstractItem (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/items/AbstractItem.js:22:25)
Apr 27 18:58:28 raspberrypi homebridge[975]: at LightbulbItem.SwitchItem (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/items/SwitchItem.js:12:23)
Apr 27 18:58:28 raspberrypi homebridge[975]: at new LightbulbItem (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/items/LightbulbItem.js:6:26)
Apr 27 18:58:28 raspberrypi homebridge[975]: at exports.Factory.parseSitemap (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/libs/ItemFactory.js:66:29)
Apr 27 18:58:28 raspberrypi homebridge[975]: at Request._callback (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/index.js:88:38)
Apr 27 18:58:28 raspberrypi homebridge[975]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/node_modules/request/request.js:185:22)
Apr 27 18:58:28 raspberrypi homebridge[975]: at Request.emit (events.js:310:20)
Apr 27 18:58:28 raspberrypi homebridge[975]: at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/node_modules/request/request.js:1154:10)
Apr 27 18:58:28 raspberrypi homebridge[975]: at Request.emit (events.js:310:20)
Apr 27 18:58:28 raspberrypi homebridge[975]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws-adv/node_modules/request/request.js:1076:12)
Apr 27 18:58:28 raspberrypi homebridge[975]: [4/27/2020, 18:58:28] Got SIGTERM, shutting down Homebridge...
Apr 27 18:58:33 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Apr 27 18:58:33 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Apr 27 18:58:43 raspberrypi systemd[1]: homebridge.service: Service RestartSec=10s expired, scheduling restart.
Apr 27 18:58:43 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 1.
Apr 27 18:58:43 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Apr 27 18:58:43 raspberrypi systemd[1]: Started Node.js HomeKit Server.

It would apreceate of anybody could help.

Thx a lot!

Michael

**Comment by bauer-andreas** [comment]
duplicates https://github.com/Sroose/homebridge-loxone-ws/issues/51
