### ISSUE TITLE
Initializing problem

### ISSUE THREAD

**Issue by ActiveByte** [Sroose/homebridge-loxone-ws#54]
Just installed this plugin but can't get it working.

```
[4/30/2020, 3:20:39 AM] Loaded config.json with 0 accessories and 1 platforms.
[4/30/2020, 3:20:39 AM] ---
[4/30/2020, 3:20:40 AM] Loaded plugin: homebridge-loxone-ws
homebridge API version: 2.5
[4/30/2020, 3:20:40 AM] Registering platform 'homebridge-loxone-ws.LoxoneWs'
[4/30/2020, 3:20:40 AM] ---
[4/30/2020, 3:20:40 AM] Loading 1 platforms...
[4/30/2020, 3:20:40 AM] [Loxone] Initializing LoxoneWs platform...
[4/30/2020, 3:20:40 AM] [Loxone] Info: rooms array not configured. Adding every room.
[4/30/2020, 3:20:40 AM] [Loxone] object
New WS: 192.168.1.27:80
[4/30/2020, 3:20:40 AM] [Loxone] Platform - Waiting 8 seconds until initial state is retrieved via WebSocket.
[4/30/2020, 3:20:40 AM] [Loxone] LOXONE WS: connect
[4/30/2020, 3:20:48 AM] [Loxone] Platform - Retrieving initial config from http://****:****@*****/data/LoxApp3.json
[4/30/2020, 3:20:48 AM] [Loxone] Platform - The widget 'Kerstboom in Living' of type Meter is an item not handled.
[4/30/2020, 3:20:48 AM] [Loxone] Platform - The widget 'Lichtsturing in Living' of type LightControllerV2 is an item not handled.
[4/30/2020, 3:20:48 AM] [Loxone] Platform - The widget 'Master helderheid of Lichtsturing in Living' of type Dimmer was skipped.
[4/30/2020, 3:20:48 AM] TypeError: Class constructor PlatformAccessory cannot be invoked without 'new'
    at LightbulbItem.AbstractItem (/usr/local/lib/node_modules/homebridge-loxone-ws/items/AbstractItem.js:22:25)
    at LightbulbItem.SwitchItem (/usr/local/lib/node_modules/homebridge-loxone-ws/items/SwitchItem.js:12:23)
    at new LightbulbItem (/usr/local/lib/node_modules/homebridge-loxone-ws/items/LightbulbItem.js:6:26)
    at exports.Factory.parseSitemap (/usr/local/lib/node_modules/homebridge-loxone-ws/libs/ItemFactory.js:66:29)
    at Request._callback (/usr/local/lib/node_modules/homebridge-loxone-ws/index.js:88:38)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/request/request.js:185:22)
    at Request.emit (events.js:316:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:316:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/request/request.js:1076:12)
[4/30/2020, 3:20:48 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by bauer-andreas** [comment]
duplicates https://github.com/Sroose/homebridge-loxone-ws/issues/51
